##############################################################
#
# Standard Pin kit makefile - normally you do not edit this file.
# Tool-specific settings are in makefile.rules.
#
# Build (from this directory):
#   make PIN_ROOT=<path to pin kit> obj-intel64/project.so
#
##############################################################

# If the tool is built out of the kit, PIN_ROOT must be specified in the make
# invocation and point to the kit root.
ifdef PIN_ROOT
CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
else
CONFIG_ROOT := ../Config
endif
include $(CONFIG_ROOT)/makefile.config
include makefile.rules
include $(TOOLS_ROOT)/Config/makefile.default.rules
