##############################################################
#
# Tool-specific makefile rules for project.so
#
##############################################################

# Tools built from <name>.cpp -> obj-intel64/<name>.so
TEST_TOOL_ROOTS := project

TEST_ROOTS :=
TOOL_ROOTS :=
SA_TOOL_ROOTS :=
APP_ROOTS :=
OBJECT_ROOTS :=
DLL_ROOTS :=
LIB_ROOTS :=
SANITY_SUBSET :=

# project.cpp includes tc_dispatch.h - rebuild when it changes.
$(OBJDIR)project$(OBJ_SUFFIX): tc_dispatch.h
