// Executes the profiling stubs generated by src/project.cpp (add_profiling_instrs)
// without Pin: see run.sh. Built non-PIE so that globals are below 2GB, like
// the absolute jump tables in the course's non-PIE test binaries.
#define main pintool_main
#include "../../src/project.cpp"
#undef main
#include <sys/mman.h>

// Targets written in asm: bump a counter and return; they touch no register
// other than what 'ret' needs, so we can check the stub preserves registers.
extern "C" { UINT64 hits_a = 0, hits_b = 0; void tgt_a(); void tgt_b(); }
asm(".text\n.p2align 4\n.globl tgt_a\ntgt_a: incq hits_a(%rip)\n ret\n"
    ".p2align 4\n.globl tgt_b\ntgt_b: incq hits_b(%rip)\n ret\n");

ADDRINT fnptr;                  // target of 'call [rip+x]' / 'call [rbx+8]'
ADDRINT table[2];               // jump table for 'jmp [rax*8+table]'
static int failures = 0;
#define CHECK(c, msg) do { if (!(c)) { printf("   FAIL: %s\n", msg); failures++; } } while (0)

// Build [stub][orig instr][ret] into the TC and return its address.
static char *build(const unsigned char *bytes, unsigned len, ADDRINT fake_addr)
{
  num_of_instr_map_entries = 0; bbl_num = 0; jump_to_orig_addr_num = 0;
  memset(bbl_map, 0, sizeof(bbl_map_t) * 16);
  static mock_ins_t mi;
  xed_decoded_inst_zero_set_mode(&mi.xedd, &dstate);
  if (xed_decode(&mi.xedd, bytes, len) != XED_ERROR_NONE) { printf("decode failed\n"); exit(1); }
  mi.addr = fake_addr;
  if (add_profiling_instrs(&mi, fake_addr, &bbl_map[0].counter, 0, false) < 0) { printf("stub failed\n"); exit(1); }
  xed_decoded_inst_t x; xed_decoded_inst_zero_set_mode(&x, &dstate); xed_decode(&x, bytes, len);
  if (add_new_instr_entry(&x, fake_addr, RegularIns) < 0) exit(1);
  unsigned char ret_b[] = {0xC3};
  xed_decoded_inst_zero_set_mode(&x, &dstate); xed_decode(&x, ret_b, 1);
  if (add_new_instr_entry(&x, fake_addr + len, RegularIns) < 0) exit(1);
  if (set_initial_estimated_new_ins_addrs_in_tc(tc) < 0 || fix_instructions_displacements() < 0 ||
      copy_instrs_to_tc(tc) < 0) { printf("layout failed\n"); exit(1); }
  tc_size = 0; for (unsigned i = 0; i < num_of_instr_map_entries; i++) tc_size += instr_map[i].size;
  if (getenv("DUMP")) { dump_tc(tc, tc_size); for (unsigned i = 0; i < num_of_instr_map_entries; i++) dump_instr_map_entry(i); }
  return tc;
}

// Run the TC with rax/rbx/rcx preset (+ one value pushed for [rsp+8] cases).
// Returns rax/rbx/rcx as seen after the TC code returned.
struct regs { UINT64 rax, rbx, rcx; };
struct io_t { UINT64 rax, rbx, rcx, pushed, r11; char *code; };   // offsets 0,8,16,24,32,40
// All inputs/outputs go through a pointer kept in RDI (the stubs and the
// asm targets never touch RDI), so moving RSP cannot break operand access.
static regs run_io(io_t *io)
{
  asm volatile("push %%rdi\n"
               "sub $128, %%rsp\n"          // keep our own red zone intact
               "pushq 24(%%rdi)\n"          // value seen as [rsp+8] inside the TC
               "mov 0(%%rdi), %%rax\n mov 8(%%rdi), %%rbx\n mov 16(%%rdi), %%rcx\n mov 32(%%rdi), %%r11\n"
               "call *40(%%rdi)\n"
               "add $136, %%rsp\n"
               "pop %%rdi\n"
               "mov %%rax, 0(%%rdi)\n mov %%rbx, 8(%%rdi)\n mov %%rcx, 16(%%rdi)\n"
               : : "D"(io) : "rax", "rbx", "rcx", "r11", "memory", "cc");
  regs r = {io->rax, io->rbx, io->rcx};
  return r;
}
static regs run(char *code, UINT64 rax, UINT64 rbx, UINT64 rcx, UINT64 pushed, UINT64 r11 = 0)
{
  io_t io = {rax, rbx, rcx, pushed, r11, code};
  return run_io(&io);
}

static unsigned slot_of(ADDRINT t) { return (t ^ (t >> 4)) & MAX_TARG_ADDRS; }

static void expect_profile(ADDRINT targ, UINT64 count, UINT64 exec, indirect_kind_t kind, ADDRINT site)
{
  unsigned s = slot_of(targ);
  CHECK(bbl_map[0].counter == exec, "BBL exec counter");
  CHECK(bbl_map[0].targ_addr[s] == targ, "recorded target address");
  CHECK(bbl_map[0].targ_count[s] == count, "recorded target count");
  CHECK(bbl_map[0].indirect_kind == kind, "indirect kind");
  CHECK(bbl_map[0].indirect_site_addr == site, "site address");
}

int main()
{
  setvbuf(stdout, 0, _IONBF, 0);   // keep printf and dump_tc() (stderr) in order
  xed_tables_init();
  max_ins_count = 4096; max_tc_size = 1 << 20;
  instr_map = (instr_map_t *)calloc(max_ins_count, sizeof(instr_map_t));
  bbl_map = (bbl_map_t *)calloc(16, sizeof(bbl_map_t));
  // TC within 2GB of the (non-PIE) globals, like allocate_and_init_memory().
  tc = (char *)mmap((void *)0x30000000, max_tc_size + 4096, PROT_READ | PROT_WRITE | PROT_EXEC,
                    MAP_PRIVATE | MAP_ANONYMOUS | MAP_FIXED_NOREPLACE, -1, 0);
  if (tc == MAP_FAILED) { perror("mmap"); return 1; }
  jump_to_orig_addr_map = (ADDRINT *)(tc + max_tc_size);
  const ADDRINT A = (ADDRINT)tgt_a, B = (ADDRINT)tgt_b, SITE = 0x401000;
  printf("tgt_a=0x%lx (slot %u)  tgt_b=0x%lx (slot %u)\n", A, slot_of(A), B, slot_of(B));
  CHECK(slot_of(A) != slot_of(B), "16-byte aligned targets should use different slots");

  KnobVerbose.v = getenv("VERB") != 0;
  { printf("1. call rax  (XED reports [rsp] as a memory operand here)\n");
    unsigned char b[] = {0xFF, 0xD0}; char *c = build(b, sizeof b, SITE);
    for (int i = 0; i < 3; i++) run(c, A, 0x1111, 0x2222, 0);
    regs r = run(c, B, 0x1111, 0x2222, 0);
    CHECK(r.rax == B && r.rbx == 0x1111 && r.rcx == 0x2222, "rax/rbx/rcx preserved");
    CHECK(hits_a == 3 && hits_b == 1, "the real call still reached its targets");
    expect_profile(A, 3, 4, IndirectCall, SITE);
    CHECK(bbl_map[0].targ_addr[slot_of(B)] == B && bbl_map[0].targ_count[slot_of(B)] == 1, "second target"); }

  { printf("2. call r11\n");
    unsigned char b[] = {0x41, 0xFF, 0xD3}; char *c = build(b, sizeof b, SITE);
    regs r = run(c, 0x33, 0x44, 0x55, 0, A);
    CHECK(r.rax == 0x33 && r.rbx == 0x44 && r.rcx == 0x55, "rax/rbx/rcx preserved");
    expect_profile(A, 1, 1, IndirectCall, SITE); }

  { printf("3. call [rbx+8]  (target operand uses RBX, which the stub saves/uses)\n");
    unsigned char b[] = {0xFF, 0x53, 0x08}; char *c = build(b, sizeof b, SITE);
    fnptr = B; regs r = run(c, 0x77, (UINT64)&fnptr - 8, 0x99, 0);
    CHECK(r.rax == 0x77 && r.rbx == (UINT64)&fnptr - 8 && r.rcx == 0x99, "rax/rbx/rcx preserved");
    expect_profile(B, 1, 1, IndirectCall, SITE); }

  { printf("4. call [rip+0x100]  (relocated by fix_rip_displacement)\n");
    unsigned char b[] = {0xFF, 0x15, 0x00, 0x01, 0x00, 0x00};
    ADDRINT fake = (ADDRINT)&fnptr - 6 - 0x100;          // so that [rip+0x100] == &fnptr
    char *c = build(b, sizeof b, fake);
    fnptr = A; run(c, 1, 2, 3, 0); run(c, 1, 2, 3, 0);
    expect_profile(A, 2, 2, IndirectCall, fake); }

  { printf("5. call [rsp+8]\n");
    unsigned char b[] = {0xFF, 0x54, 0x24, 0x08}; char *c = build(b, sizeof b, SITE);
    regs r = run(c, 5, 6, 7, B);
    CHECK(r.rax == 5 && r.rbx == 6 && r.rcx == 7, "rax/rbx/rcx preserved");
    expect_profile(B, 1, 1, IndirectCall, SITE); }

  { printf("6. jmp rax\n");
    unsigned char b[] = {0xFF, 0xE0}; char *c = build(b, sizeof b, SITE);
    regs r = run(c, B, 8, 9, 0);
    CHECK(r.rax == B && r.rbx == 8 && r.rcx == 9, "rax/rbx/rcx preserved");
    expect_profile(B, 1, 1, IndirectJump, SITE); }

  { printf("7. jmp [rax*8+table]  (jump table, index in RAX)\n");
    unsigned char b[] = {0xFF, 0x24, 0xC5, 0, 0, 0, 0};
    uint32_t d = (uint32_t)(ADDRINT)&table[0]; memcpy(&b[3], &d, 4);
    table[0] = A; table[1] = B; char *c = build(b, sizeof b, SITE);
    regs r = run(c, 1, 10, 11, 0); run(c, 1, 10, 11, 0); run(c, 0, 10, 11, 0);
    CHECK(r.rax == 1 && r.rbx == 10 && r.rcx == 11, "rax/rbx/rcx preserved");
    expect_profile(B, 2, 3, IndirectJump, SITE);
    CHECK(bbl_map[0].targ_count[slot_of(A)] == 1, "second jump-table target"); }

  { printf("8. unsupported forms are counted but their targets are not recorded\n");
    unsigned before = num_unsupported_indirect_sites;
    unsigned char fs_call[] = {0x64, 0xFF, 0x10};     // call qword ptr fs:[rax]
    unsigned char far_call[] = {0xFF, 0x18};          // call far ptr [rax]
    build(fs_call, sizeof fs_call, SITE);
    CHECK(bbl_map[0].indirect_kind == NoIndirect, "fs: call not target-profiled");
    build(far_call, sizeof far_call, SITE);
    CHECK(bbl_map[0].indirect_kind == NoIndirect, "far call not target-profiled");
    CHECK(num_unsupported_indirect_sites == before + 2, "unsupported sites counted"); }

  printf("\n-dump_tc style listing of the last supported stub (case 7):\n");
  unsigned char b[] = {0xFF, 0x24, 0xC5, 0, 0, 0, 0};
  uint32_t d = (uint32_t)(ADDRINT)&table[0]; memcpy(&b[3], &d, 4);
  build(b, sizeof b, SITE); dump_tc(tc, tc_size);

  printf(failures ? "\nFAILED (%d)\n" : "\nALL PASSED\n", failures);
  return failures != 0;
}
